export default {
  "app.title": "TubaWinUi3 CE Official Website",
  "app.shortTitle": "TubaWinUi3 CE",
  "app.version": "1.5.6",
  "app.author": "Luolan Gaga",
  "app.copyright": "© 2026 Luolan Gaga · Open source under GPL-3.0",
  "app.repository": "https://github.com/luolangaga/tubatool",
  "site.slogan": "PC hardware toolkit · Native WinUI 3",

  "nav.home": "Home",
  "nav.download": "Download",
  "nav.features": "Features",
  "nav.why": "Why Choose",
  "nav.docs": "Docs",
  "nav.about": "About",
  "nav.ranking": "Benchmarks",
  "nav.latency": "Core Latency",
  "nav.mushroom": "Mushroom Test",
  "nav.theme": "Theme",
  "nav.github": "View source on GitHub",

  "docs.cat-guide": "User Guide",
  "docs.cat-tools": "Tools",
  "docs.cat-tutorials": "Tutorials",
  "docs.cat-dev": "Developer Docs",

  "home.hero.badge": "Community Edition · Native WinUI 3 · Free · Open Source",
  "home.hero.title": "The PC Hardware Testing Toolkit",
  "home.hero.subtitle": "134 tool entries and 47 built-in tools included. Launch CPU-Z, GPU-Z, CrystalDiskMark with one click. Completely free, offline, zero data collection.",
  "home.hero.download": "Get TubaWinUi3 CE",
  "home.hero.view-github": "View on GitHub",
  "home.hero.why-choose": "Why TubaWinUi3 CE?",
  "home.hero.license": "This project is open source under GPL-3.0 and may be freely redistributed. Modified versions must remain open source and must not bundle malware.",
  "home.hero.license-link": "View statement",
  "home.hero.store-tip": "Worried about malware? Get it from the",
  "home.hero.store-name": "Microsoft Store",
  "home.hero.store-tip-end": " instead.",

  "home.features.title": "Made for PC enthusiasts",
  "home.features.subtitle": "Hardware detection, system maintenance and performance testing in one place",

  "home.section1.title": "Open source and completely free",
  "home.section1.text1": "TubaWinUi3 CE is a community rebuild (Community Edition) of the original toolbox — a free, open source and privacy-focused PC hardware toolkit for Windows! No untrusted websites needed to handle your data.",
  "home.section1.text2": "It ships with 134 tool entries, 47 of them built-in tools that need no extra downloads, including:",
  "home.section1.items": "CPU-Z processor details|GPU-Z GPU info|CrystalDiskMark disk benchmark|FurMark GPU stress test|AIDA64 system diagnostics",
  "home.section1.text3": "The toolkit is extensible - submit new tools right from the app!",

  "home.section2.title": "Hardware info at a glance",
  "home.section2.text1": "TubaWinUi3 CE queries CPU, motherboard, memory, GPU, disk and monitor data in real time via WMI on background threads - never blocking the UI.",
  "home.section2.items": "CPU model, cores/threads, frequency|GPU model, VRAM, driver version|Memory capacity, frequency, slots|Disk model, capacity, health|Monitor resolution, refresh rate",
  "home.section2.text2": "CPU-Z report overlay verification keeps the data accurate.",

  "home.section3.title": "Native WinUI 3 experience",
  "home.section3.text1": "Built with WinUI 3, embracing the Windows 11 design language natively.",
  "home.section3.items": "Mica / Acrylic backdrop materials|Light / Dark / System theme|Custom window background image|Compact mode / Turbo mode|Global search quick launch|x86 / x64 / ARM64 support|Modern responsive UI",

  "home.section4.title": "47 built-in utilities",
  "home.section4.text1": "47 built-in tools that work out of the box, covering everyday system maintenance, network diagnostics and gaming helpers.",
  "home.section4.items": "Junk cleaner - deep cleaning driven by the Winapp2 ruleset|Rogue software cleaner - context menus, startup, scheduled tasks|Game networking helper - play together without touching the router|Format converter - images, media, documents and ZIP packaging|Triple stress test - CPU / GPU / NIC load testing|Time sync - NTP server latency test and one-click resync|More: port viewer, startup manager, Windows images, AI assistant…",

  "home.gallery.title": "There is more to discover",
  "home.gallery.subtitle": "Screenshots taken from a real session: AI assistant, game monitoring overlay, game networking, format converter, ladder charts - all built in",
  "home.gallery.more": "See all 23 feature screenshots",
  "home.gallery.count": "real screenshots",

  "home.tools.title": "134 tools, organized by category",
  "home.tools.more": "and more…",

  "home.support.title": "Support us!",
  "home.support.text1": "If you like TubaWinUi3 CE, feel free to",
  "home.support.star": "star the repo",
  "home.support.feedback": "submit feedback",
  "home.support.contribute": "contribute code",
  "home.support.text2": "or submit new tools.",

  "home.footer.credit1": "Design inspired by",
  "home.footer.credit2": "UI controls powered by",
  "home.footer.credit-link": "WinUIonWeb",

  "features.title": "Feature Tour",
  "features.subtitle": "23 real screenshots - see what TubaWinUi3 CE can do, from hardware detection and benchmarks to system maintenance",
  "features.filter-label": "Filter features by category",
  "features.empty": "Nothing in this category yet",
  "features.prev": "Previous",
  "features.next": "Next",
  "features.close": "Close",
  "features.view-doc": "Read the docs",

  "features.stat.tools": "tool entries",
  "features.stat.builtin": "built-in tools",
  "features.stat.community": "community tools",
  "features.stat.arch": "supported architectures",

  "features.cat.all": "All",
  "features.cat.hardware": "Hardware",
  "features.cat.perf": "Benchmarks",
  "features.cat.maintain": "Maintenance",
  "features.cat.network": "Network",
  "features.cat.ai": "AI Assistant",
  "features.cat.shell": "Interface",

  "features.home.title": "The tool library",
  "features.home.desc": "134 tools laid out by category: card browsing, star favourites, context menus and one-click launch, plus instant global search.",
  "features.home.tags": "Category filter|Global search|Star favourites|One-click launch",

  "features.hardware.title": "Hardware at a glance",
  "features.hardware.desc": "Reads motherboard, CPU, memory, GPU, NPU, monitor, disk, audio and network details in one WMI pass, with CPU-Z report override verification.",
  "features.hardware.tags": "CPU / motherboard|Memory / slots|GPU / driver|Monitor / disks",

  "features.builtin-tools.title": "47 built-in tools",
  "features.builtin-tools.desc": "No external executables needed. Organized into system, hardware, utility, network and gaming groups.",
  "features.builtin-tools.tags": "System tools|Hardware tools|Utilities|Network / gaming",

  "features.ai-assistant.title": "AI assistant",
  "features.ai-assistant.desc": "Describe the problem in plain language and the built-in agent diagnoses it, tunes settings, runs operations and searches the web - asking first before anything risky.",
  "features.ai-assistant.tags": "Conversational diagnosis|Tool calling|Full-access mode|Custom models",

  "features.game-monitor.title": "Game monitoring overlay",
  "features.game-monitor.desc": "Drag widgets to design your own overlay, then layer it over the game window for live FPS, CPU/GPU temperature, clocks, power, VRAM and memory usage.",
  "features.game-monitor.tags": "Live FPS|Temperature / power|Draggable layout|Session recording",

  "features.game-tunnel.title": "Game networking helper",
  "features.game-tunnel.desc": "Puts two PCs on the same virtual LAN so Minecraft, Terraria, Stardew Valley and Don't Starve just connect - no public IP, no router changes.",
  "features.game-tunnel.tags": "Virtual LAN|Invite code|Game presets|TCP / UDP",

  "features.stress-test.title": "Triple stress test",
  "features.stress-test.desc": "CPU, GPU and NIC stress testing with live temperature, clock, power and throughput monitoring. FurMark render API, resolution, MSAA and OSD are configurable, and reports can be exported.",
  "features.stress-test.tags": "CPU stress|GPU stress|NIC stress|Export report",

  "features.gpu-stress-test.title": "Mushroom test",
  "features.gpu-stress-test.desc": "Voxel fractal rendering as a GPU stress test with easy, medium and extreme levels, overlaying frame rate, frame time and GPU model in real time.",
  "features.gpu-stress-test.tags": "Fractal rendering|Three levels|Live frame rate|GPU stability",

  "features.benchmark-cloud.title": "Cloud benchmark ranking",
  "features.benchmark-cloud.desc": "Upload your results with one click and compare gaming and office scores, plus individual CPU, GPU, memory and disk scores, against the community.",
  "features.benchmark-cloud.tags": "Gaming / office|Per-part scores|Same-config compare|My records",

  "features.cpu-ranking.title": "CPU / GPU ladder charts",
  "features.cpu-ranking.desc": "Built-in ladder data split between desktop and laptop, filterable by Intel, AMD, Apple and Qualcomm, with multi-core and single-core scores at a glance.",
  "features.cpu-ranking.tags": "Multi / single core|Desktop / laptop|Brand filter|Refreshable",

  "features.quick-device-check.title": "One-click device check",
  "features.quick-device-check.desc": "An 8-step wizard walks you through a brand-new PC, from the physical inspection checklist to the hardware itself, so nothing gets missed.",
  "features.quick-device-check.tags": "8-step wizard|Inspection checklist|Item by item",

  "features.traffic-monitor.title": "Traffic monitor",
  "features.traffic-monitor.desc": "Pick an adapter to see download/upload speed and latency per connection, with whole-adapter throughput charts, snapshot recording and a tray mode.",
  "features.traffic-monitor.tags": "Per-connection|Throughput charts|Snapshot recording|Tray resident",

  "features.speed-test.title": "Speed test",
  "features.speed-test.desc": "Multi-threaded testing against several nodes, with live charts for download, upload, latency and jitter.",
  "features.speed-test.tags": "Multiple nodes|Live charts|Latency / jitter",

  "features.port-viewer.title": "Port viewer",
  "features.port-viewer.desc": "Scans every TCP and UDP connection with state, process and PID, so you can find the conflict and end the owning process right there.",
  "features.port-viewer.tags": "TCP / UDP|Process / PID|End owning process",

  "features.junk-cleaner.title": "Junk cleaner",
  "features.junk-cleaner.desc": "Scans app caches, temp files and registry leftovers using the Winapp2 rule database (4000+ rules built in). Review every item before cleaning - fully offline.",
  "features.junk-cleaner.tags": "Winapp2 rules|Cache / temp files|Registry leftovers|Preinstalled apps",

  "features.rogue-cleaner.title": "Rogue software cleaner",
  "features.rogue-cleaner.desc": "Cleans rogue context menus, startup entries, scheduled tasks, services, browser plugins and file-association leftovers. Everything is backed up first and restorable from the recovery centre.",
  "features.rogue-cleaner.tags": "Context menus|Startup / tasks|Plugin leftovers|Recovery centre",

  "features.startup-manager.title": "Startup manager",
  "features.startup-manager.desc": "Scans registry, startup folders and scheduled tasks for every auto-start entry, flags the risky ones and disables them on the spot.",
  "features.startup-manager.tags": "Full scan|Risk flags|One-click disable",

  "features.format-converter.title": "Format converter",
  "features.format-converter.desc": "Drop files in to convert images, audio, video, Word, Excel, PowerPoint, PDF, Markdown, TXT, HTML and JSON - or pack anything into a ZIP.",
  "features.format-converter.tags": "Drag and drop|Images / media|Office documents|Zip packaging",

  "features.windows-image.title": "Windows image download",
  "features.windows-image.desc": "Three routes in one: official Microsoft ISO links, community mirrors and UUP Dump - so LTSC, Enterprise, Education, IoT and Server builds can become ISOs too.",
  "features.windows-image.tags": "Official ISOs|UUP Dump|ESD to ISO",

  "features.time-sync.title": "Time sync",
  "features.time-sync.desc": "Built-in NTP servers from Alibaba Cloud, Tencent Cloud, the national time service centre and Cloudflare - test latency first, then switch, resync and repair the Windows Time service.",
  "features.time-sync.tags": "Server latency test|One-click resync|Service repair|Health report",

  "features.favorites.title": "Favourites",
  "features.favorites.desc": "Tools you use most are recommended automatically, and starred tools can be reordered by dragging so your daily drivers sit right where you want them.",
  "features.favorites.tags": "Smart ordering|Drag to reorder|Shared star state",

  "features.community.title": "Community tool plugins",
  "features.community.desc": "Search, download and install community-contributed tools right inside the app - or submit your own setup to share with everyone else.",
  "features.community.tags": "One-click install|Category filter|Submit your own",

  "features.settings.title": "Personalization",
  "features.settings.desc": "Theme and backdrop, interface language, navigation layout, default landing page, compact list mode and turbo mode - tune the toolbox to fit you.",
  "features.settings.tags": "Theme / backdrop|Interface language|Navigation layout|Turbo mode",

  "download.title": "Download TubaWinUi3 CE",
  "download.subtitle": "Free · Offline · Auto-detects your architecture",
  "download.version": "Latest version",
  "download.loading": "Loading…",
  "download.detect-arch": "Detected architecture:",
  "download.recommended": "Recommended",
  "download.portable": "Portable",
  "download.portable-desc": "Extract and run - no install, perfect for USB sticks",
  "download.lite": "Lite",
  "download.lite-badge": "x64 only",
  "download.lite-desc": "Bundles only the essential tools (CPU-Z / GPU-Z / HWiNFO / FurMark and a few more) for a much smaller download - the full tool set can be added later in Settings",
  "download.wd-warning": "The portable build may be flagged by Windows Defender as a false positive. Consider the installer version, or temporarily disable Defender before downloading.",
  "download.setup": "Installer",
  "download.setup-desc": "Classic installer with shortcuts and Start Menu entries",
  "download.store": "Microsoft Store",
  "download.store-desc": "Install from the official Microsoft Store with auto-updates",
  "download.preview": "Preview",
  "download.preview-desc": "Pulls the newest published build straight from GitHub / GitCode - new changes land here first, and so do the bugs",
  "download.preview-warning": "This is a test build: the changes have not been fully validated yet, so you may run into some odd problems. Use the stable builds above if you want reliability",
  "download.prerelease": "Pre-release",
  "download.cli": "Command Line Install",
  "download.cli-desc": "Install with a Windows package manager — updates managed automatically",
  "download.winget": "Winget (built into Windows)",
  "download.scoop": "Scoop",
  "download.gitcode": "GitCode",
  "download.gitcode-badge": "CN Recommended",
  "download.now": "Download Now",
  "download.github": "GitHub",
  "download.mirror": "Mirror",
  "download.cloud": "Cloud drives",
  "download.cloud-sub": "All architectures",
  "download.quark": "Quark",
  "download.baidu": "Baidu",
  "download.older-title": "Need an older version?",
  "download.gh-releases": "GitHub Releases",
  "download.gc-releases": "GitCode Releases",
  "download.sys-req": "System requirements",
  "download.sys-os": "OS",
  "download.sys-os-value": "Windows 10 1809+",
  "download.sys-arch": "Architecture",
  "download.sys-arch-value": "x64 / ARM64",
  "download.sys-runtime": "Runtime",
  "download.sys-runtime-value": "No extra runtime needed",
  "download.sys-disk": "Disk space",
  "download.sys-disk-value": "About 500 MB",

  "thanks.title": "Thank you for downloading TubaWinUi3 CE",
  "thanks.subtitle": "Download started",
  "thanks.heading": "Thanks for using TubaWinUi3 CE!",
  "thanks.desc": "We hope this toolkit helps you understand your PC better. If you like it, consider starring the repo on GitHub.",
  "thanks.download-started": "Download started",
  "thanks.download-started-desc": "Your browser opened the download task and the file is being transferred.",
  "thanks.type": "Type",
  "thanks.source": "Source",
  "thanks.meta-version": "Selected version",
  "thanks.meta-arch": "Selected architecture",
  "thanks.meta-type": "Download type",
  "thanks.meta-source": "Download source",
  "thanks.note-title": "Download did not start?",
  "thanks.note": "If the download did not start automatically, click the button below to retry.",
  "thanks.again": "Download again",
  "thanks.back-home": "Back to home",

  "about.title": "About TubaWinUi3 CE",
  "about.subtitle": "Community Edition of the original toolbox — a free, open source, privacy-focused PC hardware toolkit",
  "about.appearance": "Appearance",
  "about.theme": "Theme",
  "about.theme-desc": "Choose the site display mode",
  "about.use-system": "Use system setting",
  "about.light": "Light",
  "about.dark": "Dark",
  "about.nav-position": "Navigation pane position",
  "about.nav-position-desc": "Select how the navigation bar is displayed",
  "about.nav-auto": "Auto",
  "about.nav-left": "Left",
  "about.nav-top": "Top",
  "about.community": "Community & source",
  "about.repo-desc": "Star, feedback and contributions are welcome",
  "about.license": "License",
  "about.license-title": "GPL-3.0 License",
  "about.license-desc": "Open source under GPL-3.0, free to redistribute. Modified versions must remain open source and must never bundle malware.",
  "about.dmca": "DMCA / malware bundling statement",
  "about.thanks": "Special thanks",
  "about.thanks-desc": "This site is built with WinUIonWeb web WinUI controls",
  "about.winui-on-web": "WinUIonWeb - bringing WinUI to the web",
  "about.open-repo": "Open repository",

  "search.placeholder": "Search docs and site content…",
  "search.title": "Search",
  "search.results-for": "Results for",
  "search.results-count": "results",
  "search.empty-query": "Type keywords to search docs, tutorials and site content",
  "search.no-results": "No results found",
  "search.no-results-desc": "Try different keywords, e.g. CPU-Z, disk, blue screen, hardware info",

  "why.title": "Why Choose TubaWinUi3 CE?",
  "why.subtitle": "Comprehensive comparison against the original toolbox — TubaWinUi3 CE leads in download experience, UI design, compatibility, features, and AI capabilities",
  "why.winner": "Better",
  "why.legacy": "Original",

  "why.dl.title": "Download Methods",
  "why.dl.subtitle": "Multi-channel high-speed downloads vs single slow website",
  "why.dl.winItems": "Winget one-command CLI install|Microsoft Store install with auto-updates|GitCode high-speed download for China|GitHub Releases download|Quark / Baidu cloud drive download",
  "why.dl.legacyItems": "Official website only — slow access from China|No package manager support, no auto-updates|Single download channel, prone to server overload failures",

  "why.ui.title": "Software Interface",
  "why.ui.subtitle": "WinUI 3 native Fluent Design vs legacy EPL (易语言) UI",
  "why.ui.winItems": "Built with WinUI 3, native Windows 11 design language|Mica / Acrylic backdrop materials|Smooth page transitions and control animations|Light / Dark / System theme support|Custom window background images|Modern responsive layout",
  "why.ui.legacyItems": "Traditional EPL (易语言)-based UI, outdated visuals|No backdrop materials, no animation transitions|Only basic dark mode toggle|Limited control styling options",

  "why.utf8.title": "UTF-8 Compatibility",
  "why.utf8.subtitle": "Perfect Unicode support vs runtime exceptions with UTF-8",
  "why.utf8.winItems": "Native UTF-8 encoding — paths and filenames display correctly|Chinese directory names render perfectly|.NET 10 runtime with native Unicode handling",
  "why.utf8.legacyItems": "Runtime exceptions when Windows UTF-8 global support is enabled|EPL defaults to ANSI encoding with poor UTF-8 compatibility|Chinese paths may display garbled characters or fail to resolve",

  "why.tools.title": "FluentUI Built-in Tools",
  "why.tools.subtitle": "47 built-in tools vs limited basic utilities",
  "why.tools.winItems": "Junk cleaner — deep cleaning driven by the Winapp2 ruleset|Rogue software cleaner — context menus, startup, scheduled tasks|Game networking helper — play together without a public IP|Format converter — images, media, documents and ZIP packaging|Triple stress test — CPU / GPU / NIC load testing with reports|Port viewer, startup manager, time sync, Windows image download|AI assistant, CPU / GPU ladder charts, cloud benchmark ranking",
  "why.tools.legacyItems": "Limited number of built-in tools|Inconsistent tool interface styles|Some tools have only basic functionality",

  "why.ai.title": "AI-Powered",
  "why.ai.subtitle": "Built-in AI assistant to help solve PC problems",
  "why.ai.winItems": "Built-in AI agent for hardware and system questions|Support for multiple AI model integrations|Natural language interaction, lower barrier to entry|Continuously iterated AI capabilities",
  "why.ai.legacyItems": "No AI features|Must search and troubleshoot issues manually",

  "why.summary.title": "TubaWinUi3 CE — The Next-Gen PC Hardware Toolkit",
  "why.summary.text": "From download experience to daily use, TubaWinUi3 CE brings a quantum leap in every dimension. If you're still using the original, it's time to upgrade.",
  "why.summary.download": "Download TubaWinUi3 CE Now",

  "rank.title": "Benchmark Ranking",
  "rank.subtitle": "Community-submitted performance benchmarks from the TubaWinUi3 CE community — compare your PC with users worldwide",
  "rank.info-title": "How to submit your score?",
  "rank.info-message": "Download and install TubaWinUi3 CE, run the built-in \"Performance Test\" to complete all test items, then click \"Upload Ranking\" to submit your data to the community leaderboard.",
  "rank.sort.gaming": "Gaming",
  "rank.sort.office": "Office",
  "rank.sort.cpu": "CPU Multi-core",
  "rank.sort.gpu": "GPU Render",
  "rank.sort.disk": "Disk Read",
  "rank.sort.browser": "Browser",
  "rank.search-placeholder": "Search CPU / GPU / username…",
  "rank.refresh": "Refresh",
  "rank.retry": "Retry",
  "rank.loading": "Loading leaderboard…",
  "rank.empty": "No matching benchmarks found. Try another keyword.",
  "rank.game": "Gaming",
  "rank.office": "Office",
  "rank.entries": "entries",
  "rank.page": "Page",
  "rank.prev": "Prev",
  "rank.next": "Next",
  "rank.close": "Close",
  "rank.report-title": "'s report",
  "rank.detail.cpu": "CPU",
  "rank.detail.gpu": "GPU",
  "rank.detail.motherboard": "Motherboard",
  "rank.detail.memory": "Memory",
  "rank.detail.disk": "Storage",
  "rank.detail.os": "OS",
  "rank.detail.cpu-single": "CPU single-core",
  "rank.detail.cpu-multi": "CPU multi-core",
  "rank.detail.gpu-render": "GPU render",
  "rank.detail.memory-cap": "Memory capacity",
  "rank.detail.disk-read": "Disk seq read",
  "rank.detail.disk-write": "Disk seq write",
  "rank.detail.disk-4k-read": "Disk 4K read",
  "rank.detail.disk-4k-write": "Disk 4K write",
  "rank.detail.browser": "Browser",
  "rank.detail.submitted": "Submitted",
  "rank.detail-loading": "Loading hardware details…",
  "rank.detail-load-failed": "Failed to load hardware details. Try again later.",

  "latency.title": "Core-to-Core Latency",
  "latency.subtitle": "Community-submitted CPU core-to-core latency heatmaps — compare inter-core communication latency across processors",
  "latency.search-placeholder": "Search CPU / username…",
  "latency.refresh": "Refresh",
  "latency.retry": "Retry",
  "latency.loading": "Loading heatmaps…",
  "latency.empty": "No core-to-core latency heatmaps yet",
  "latency.view": "Click to view heatmap",
  "latency.total": "heatmaps",
  "latency.close": "Close",
  "latency.dialog-title": "Core-to-Core Latency Heatmap",

  "mushroom.title": "Mushroom Stress Test",
  "mushroom.start": "Click to start test"
}
