export default {
  "app.title": "图吧工具箱CE 官方网站",
  "app.shortTitle": "图吧工具箱CE官网",
  "app.version": "1.5.6",
  "app.author": "罗澜嘎嘎",
  "app.copyright": "© 2026 罗澜嘎嘎 · 基于 GPL-3.0 协议开源",
  "app.repository": "https://github.com/luolangaga/tubatool",
  "site.slogan": "PC 硬件检测利器 · WinUI 3 原生工具箱",

  "nav.home": "首页",
  "nav.download": "下载",
  "nav.features": "功能展示",
  "nav.why": "为什么选择",
  "nav.docs": "文档",
  "nav.about": "关于",
  "nav.ranking": "跑分排行",
  "nav.latency": "核间延迟",
  "nav.mushroom": "毒蘑菇测试",
  "nav.theme": "主题",
  "nav.github": "在 GitHub 查看源码",

  "docs.cat-guide": "使用指南",
  "docs.cat-tools": "工具说明",
  "docs.cat-tutorials": "使用教程",
  "docs.cat-dev": "开发文档",

  "home.hero.badge": "社区重构版 · WinUI 3 原生 · 完全免费 · 开源",
  "home.hero.title": "PC 硬件检测利器",
  "home.hero.subtitle": "收录 134 个工具条目、47 款内置工具，一键启动 CPU-Z、GPU-Z、CrystalDiskMark，完全免费离线运行，零数据收集",
  "home.hero.download": "获取图吧工具箱CE",
  "home.hero.view-github": "查看 GitHub",
  "home.hero.why-choose": "为什么选择图吧工具箱CE？",
  "home.hero.license": "本项目基于 GPL-3.0 协议开源，允许自由分发。修改版须开源，禁止捆绑恶意软件。",
  "home.hero.license-link": "查看声明",
  "home.hero.store-tip": "如果你害怕下载到病毒可以到",
  "home.hero.store-name": "微软应用商店",
  "home.hero.store-tip-end": "下载",

  "home.features.title": "为电脑爱好者而生",
  "home.features.subtitle": "一站式解决硬件检测、系统维护与性能测试需求",

  "home.section1.title": "开源且完全免费",
  "home.section1.text1": "图吧工具箱CE 是原版图吧工具箱的社区重构版，免费、开源且注重隐私的 PC 硬件工具集，运行在 Windows 平台！无需使用各种不可信的网站来处理你的数据。",
  "home.section1.text2": "它自带 134 个工具条目，其中 47 款是免下载的内置工具，包括：",
  "home.section1.items": "CPU-Z 处理器详细信息|GPU-Z 显卡参数检测|CrystalDiskMark 磁盘测速|FurMark 显卡压力测试|AIDA64 综合硬件检测",
  "home.section1.text3": "工具集是可扩展的，你可以在软件内直接提交新工具！",

  "home.section2.title": "硬件信息一目了然",
  "home.section2.text1": "图吧工具箱CE通过 WMI 实时查询处理器、主板、内存、显卡、硬盘、显示器等硬件数据，后台线程执行，不阻塞 UI。",
  "home.section2.items": "处理器型号、核心/线程数、频率|显卡型号、显存、驱动版本|内存容量、频率、插槽信息|硬盘型号、容量、健康状态|显示器分辨率、刷新率",
  "home.section2.text2": "还支持 CPU-Z 报表覆盖验证，确保数据准确可靠。",

  "home.section3.title": "WinUI 3 原生体验",
  "home.section3.text1": "图吧工具箱CE采用 WinUI 3 打造，原生拥抱 Windows 11 设计语言。",
  "home.section3.items": "Mica / Acrylic 毛玻璃背景|亮色 / 暗色 / 跟随系统主题|自定义窗口背景图片|紧凑模式 / 快速模式|全局搜索快速启动|x86 / x64 / ARM64 全架构|现代化响应式界面",

  "home.section4.title": "47 款内置实用工具",
  "home.section4.text1": "图吧工具箱CE自带 47 款内置工具，无需额外下载即可使用，覆盖系统维护、网络诊断与游戏辅助的常见场景。",
  "home.section4.items": "垃圾清理 — Winapp2 规则库驱动的深度清理|流氓软件的克星 — 右键菜单 / 自启动 / 计划任务|游戏联机助手 — 不开路由器也能和朋友联机|格式转换 — 图片、音视频、文档、打包 ZIP|一键三烤 — CPU / GPU / 网卡压力测试|时间同步 — NTP 服务器测速与一键校时|更多：端口占用、启动项管理、Windows 镜像、AI 助手…",

  "home.gallery.title": "更多功能，等你发现",
  "home.gallery.subtitle": "截图来自实机运行：AI 助手、游戏监控覆盖层、游戏联机、格式转换、天梯图…全部内置，装完就能用",
  "home.gallery.more": "查看全部 23 张功能截图",
  "home.gallery.count": "张实机截图",

  "home.tools.title": "134 个工具，按分类一目了然",
  "home.tools.more": "还有更多…",

  "home.support.title": "支持我们！",
  "home.support.text1": "如果你喜欢图吧工具箱CE，欢迎",
  "home.support.star": "给个 Star",
  "home.support.feedback": "提交反馈",
  "home.support.contribute": "贡献代码",
  "home.support.text2": "或提交新工具。",

  "home.footer.credit1": "网站设计灵感来源于",
  "home.footer.credit2": "界面控件基于",
  "home.footer.credit-link": "WinUIonWeb",

  "features.title": "功能展示",
  "features.subtitle": "23 张实机截图，从硬件检测、性能测试到系统维护，一次看清图吧工具箱CE 能做什么",
  "features.filter-label": "按分类筛选功能",
  "features.empty": "该分类下暂无内容",
  "features.prev": "上一张",
  "features.next": "下一张",
  "features.close": "关闭",
  "features.view-doc": "查看相关文档",

  "features.stat.tools": "工具条目",
  "features.stat.builtin": "内置工具",
  "features.stat.community": "社区工具",
  "features.stat.arch": "支持架构",

  "features.cat.all": "全部",
  "features.cat.hardware": "硬件检测",
  "features.cat.perf": "性能测试",
  "features.cat.maintain": "系统维护",
  "features.cat.network": "网络与联机",
  "features.cat.ai": "AI 助手",
  "features.cat.shell": "界面与体验",

  "features.home.title": "工具总库",
  "features.home.desc": "134 个工具按分类平铺展示，卡片式浏览、星标收藏、右键菜单、一键打开，支持全局搜索秒级定位。",
  "features.home.tags": "分类筛选|全局搜索|星标收藏|一键运行",

  "features.hardware.title": "硬件信息总览",
  "features.hardware.desc": "通过 WMI 一次性读取主板、处理器、内存、显卡、NPU、显示器、硬盘、声卡与网卡参数，支持 CPU-Z 报表覆盖校验。",
  "features.hardware.tags": "处理器 / 主板|内存 / 插槽|显卡 / 驱动|显示器 / 硬盘",

  "features.builtin-tools.title": "47 款内置工具",
  "features.builtin-tools.desc": "无需外部程序，开箱即用。按系统工具、硬件工具、实用工具、网络工具、游戏工具五个分类整理。",
  "features.builtin-tools.tags": "系统工具|硬件工具|实用工具|网络 / 游戏",

  "features.ai-assistant.title": "AI 助手",
  "features.ai-assistant.desc": "内置智能体，用自然语言描述问题即可诊断故障、优化设置、执行操作并联网搜索；危险操作会先征求确认。",
  "features.ai-assistant.tags": "对话式诊断|工具调用|完全访问模式|自定义模型",

  "features.game-monitor.title": "游戏监控覆盖层",
  "features.game-monitor.desc": "拖动组件自由设计覆盖层布局，叠加到游戏窗口实时显示 FPS、CPU / GPU 温度、频率、功耗、显存与内存占用。",
  "features.game-monitor.tags": "实时 FPS|温度 / 功耗|布局可拖拽|数据记录",

  "features.game-tunnel.title": "游戏联机助手",
  "features.game-tunnel.desc": "把两台电脑接进同一个虚拟局域网，我的世界、泰拉瑞亚、星露谷、饥荒等游戏直接联机，不用公网 IP、不改路由器。",
  "features.game-tunnel.tags": "虚拟局域网|邀请码入网|内置游戏预设|TCP / UDP",

  "features.stress-test.title": "一键三烤",
  "features.stress-test.desc": "CPU / GPU / 网卡压力测试，实时监控温度、频率、功耗与网卡吞吐；FurMark 渲染 API、分辨率、MSAA、OSD 参数可调，支持导出报告。",
  "features.stress-test.tags": "CPU 烤机|GPU 烤机|网卡烤机|导出报告",

  "features.gpu-stress-test.title": "毒蘑菇测试",
  "features.gpu-stress-test.desc": "体素分形渲染压力测试，轻松 / 中等 / 变态三档压力，实时叠加帧率、帧耗时与显卡型号。",
  "features.gpu-stress-test.tags": "分形渲染|三档压力|实时帧率|显卡稳定性",

  "features.benchmark-cloud.title": "云端跑分排行",
  "features.benchmark-cloud.desc": "跑完性能测试可一键上传云端，与社区用户对比游戏性能、办公性能以及 CPU、GPU、内存、硬盘分项得分。",
  "features.benchmark-cloud.tags": "游戏 / 办公分|分项硬件分|同配置对比|我的记录",

  "features.cpu-ranking.title": "CPU / GPU 天梯图",
  "features.cpu-ranking.desc": "内置天梯图数据，桌面与笔记本分开，支持 Intel / AMD / Apple / Qualcomm 筛选，多核、单核分数一览。",
  "features.cpu-ranking.tags": "多核 / 单核|桌面 / 笔记本|按品牌筛选|随时刷新",

  "features.quick-device-check.title": "一键验机",
  "features.quick-device-check.desc": "8 步向导带你把新电脑从外观到硬件逐项核验一遍，附外观检查清单，装机、验机不再漏项。",
  "features.quick-device-check.tags": "8 步向导|外观检查清单|逐项核验",

  "features.traffic-monitor.title": "流量监控器",
  "features.traffic-monitor.desc": "选择网卡查看每个连接进程的下载 / 上传速度与延迟，整卡吞吐折线统计，支持快照录制回放与最小化到托盘。",
  "features.traffic-monitor.tags": "按连接监控|整卡吞吐曲线|快照录制|托盘常驻",

  "features.speed-test.title": "网速测试",
  "features.speed-test.desc": "多线程测速，支持浙大、Ookla、Cloudflare 多个测速节点，实时曲线显示下载 / 上传 / 延迟 / 抖动。",
  "features.speed-test.tags": "多节点选择|实时曲线|延迟 / 抖动",

  "features.port-viewer.title": "端口占用",
  "features.port-viewer.desc": "扫描全部 TCP / UDP 连接，显示状态、进程与 PID，定位端口冲突后可直接结束占用进程。",
  "features.port-viewer.tags": "TCP / UDP|进程 / PID|结束占用进程",

  "features.junk-cleaner.title": "垃圾清理",
  "features.junk-cleaner.desc": "基于 Winapp2 规则库（内置 4000+ 条规则）扫描应用缓存、临时文件与注册表残留，清理前可逐项确认，离线开箱即用。",
  "features.junk-cleaner.tags": "Winapp2 规则库|缓存 / 临时文件|注册表残留|预装应用清理",

  "features.rogue-cleaner.title": "流氓软件的克星",
  "features.rogue-cleaner.desc": "扫描清理流氓右键菜单、自启动项、计划任务、服务、浏览器插件与文件关联残留；所有处理先备份，可随时在恢复中心还原。",
  "features.rogue-cleaner.tags": "右键菜单|自启动 / 计划任务|插件残留|恢复中心",

  "features.startup-manager.title": "启动项管理",
  "features.startup-manager.desc": "扫描注册表、启动文件夹、计划任务等所有开机自启项，标出风险条目并可直接禁用，开机变慢一眼找到原因。",
  "features.startup-manager.tags": "全量扫描|风险标记|一键禁用",

  "features.format-converter.title": "格式转换",
  "features.format-converter.desc": "拖入文件即可转换图片、音视频、Word / Excel / PPT / PDF、Markdown、TXT、HTML、JSON，任意文件也能打包成 ZIP。",
  "features.format-converter.tags": "拖放转换|图片 / 音视频|Office 文档|打包 ZIP",

  "features.windows-image.title": "Windows 镜像下载",
  "features.windows-image.desc": "微软官方 ISO 直链、社区镜像源与 UUP Dump 三条路走通，LTSC / 企业版 / 教育版 / IoT / Server 也能从 UUP 转出 ISO。",
  "features.windows-image.tags": "官方 ISO|UUP Dump|ESD 转 ISO",

  "features.time-sync.title": "时间同步",
  "features.time-sync.desc": "内置阿里云、腾讯云、国家授时中心、Cloudflare 等 NTP 服务器，先测速再切换，一键校时并修复 Windows 时间服务。",
  "features.time-sync.tags": "服务器测速|一键校时|服务修复|体检报告",

  "features.favorites.title": "常用与收藏",
  "features.favorites.desc": "按使用频率智能推荐常用工具，收藏的工具可拖拽排序，把每天都要用的几个工具放在最顺手的位置。",
  "features.favorites.tags": "频率智能排序|拖拽排序|星标互通",

  "features.community.title": "社区工具插件",
  "features.community.desc": "社区贡献的工具插件可在应用内直接搜索、下载、安装，也可以把自己整理的工具提交上去分享给其他人。",
  "features.community.tags": "一键安装|分类筛选|提交自己的工具",

  "features.settings.title": "个性化设置",
  "features.settings.desc": "主题与背景、界面语言、导航布局、默认启动页、简洁列表模式与快速模式，把工具箱调成顺手的样子。",
  "features.settings.tags": "主题 / 背景|界面语言|导航布局|快速模式",

  "download.title": "下载图吧工具箱CE",
  "download.subtitle": "免费 · 离线运行 · 自动识别架构",
  "download.version": "最新版本",
  "download.loading": "加载中…",
  "download.detect-arch": "检测到架构：",
  "download.recommended": "推荐",
  "download.portable": "便携版",
  "download.portable-desc": "解压即用，无需安装，适合 U 盘随身携带",
  "download.lite": "精简版",
  "download.lite-badge": "仅 x64",
  "download.lite-desc": "只内置必要工具（CPU-Z / GPU-Z / HWiNFO / FurMark 等），体积更小，其余工具可在设置中升级为完整版内核",
  "download.wd-warning": "便携版可能会被 Windows Defender 误报，推荐使用安装包版，或暂时关闭 Defender 后再下载",
  "download.setup": "安装包",
  "download.setup-desc": "传统安装方式，自动创建快捷方式和开始菜单",
  "download.store": "微软商店",
  "download.store-desc": "通过官方 Microsoft Store 下载安装，自动更新",
  "download.preview": "预览版 (Preview)",
  "download.preview-desc": "直接取 GitHub / GitCode 上最新发布的构建，新改动最快拿到，也最先遇到问题",
  "download.preview-warning": "这是测试版：改动尚未经过充分验证，可能会遇到一些奇怪的问题。追求稳定请使用上面的正式版",
  "download.prerelease": "预发布",
  "download.cli": "命令行安装",
  "download.cli-desc": "使用 Windows 包管理器一键安装，自动管理更新",
  "download.winget": "Winget（Windows 自带）",
  "download.scoop": "Scoop",
  "download.gitcode": "GitCode",
  "download.gitcode-badge": "国内推荐",
  "download.now": "立即下载",
  "download.github": "GitHub",
  "download.mirror": "镜像",
  "download.cloud": "网盘下载",
  "download.cloud-sub": "全部架构",
  "download.quark": "夸克网盘",
  "download.baidu": "百度网盘",
  "download.older-title": "需要旧版本？",
  "download.gh-releases": "GitHub Releases",
  "download.gc-releases": "GitCode Releases",
  "download.sys-req": "系统要求",
  "download.sys-os": "操作系统",
  "download.sys-os-value": "Windows 10 1809+",
  "download.sys-arch": "架构",
  "download.sys-arch-value": "x64 / ARM64",
  "download.sys-runtime": "运行时",
  "download.sys-runtime-value": "无需额外安装",
  "download.sys-disk": "磁盘空间",
  "download.sys-disk-value": "约 500 MB",

  "thanks.title": "感谢下载图吧工具箱CE",
  "thanks.subtitle": "下载已开始",
  "thanks.heading": "感谢使用图吧工具箱CE！",
  "thanks.desc": "我们相信这款工具集能帮助你更好地了解自己的电脑。如果觉得好用，欢迎到 GitHub 给个项目 Star。",
  "thanks.download-started": "下载已开始",
  "thanks.download-started-desc": "浏览器已打开下载任务，文件正在传输中。",
  "thanks.type": "类型",
  "thanks.source": "来源",
  "thanks.meta-version": "你选择的版本",
  "thanks.meta-arch": "你选择的架构",
  "thanks.meta-type": "下载类型",
  "thanks.meta-source": "下载源",
  "thanks.note-title": "下载没有开始？",
  "thanks.note": "如果浏览器没有自动开始下载，请点击下方按钮重试。",
  "thanks.again": "再次下载",
  "thanks.back-home": "返回首页",

  "about.title": "关于图吧工具箱CE",
  "about.subtitle": "原版图吧工具箱的社区重构版（Community Edition）· 免费、开源、注重隐私的 PC 硬件工具集",
  "about.appearance": "外观",
  "about.theme": "主题",
  "about.theme-desc": "选择站点的显示模式",
  "about.use-system": "跟随系统",
  "about.light": "浅色",
  "about.dark": "深色",
  "about.nav-position": "导航栏位置",
  "about.nav-position-desc": "选择导航栏的显示方式",
  "about.nav-auto": "自动",
  "about.nav-left": "左侧",
  "about.nav-top": "顶部",
  "about.community": "社区与源码",
  "about.repo-desc": "欢迎 Star、反馈与贡献代码",
  "about.license": "开源协议",
  "about.license-title": "GPL-3.0 许可证",
  "about.license-desc": "本项目基于 GPL-3.0 协议开源，允许自由分发；修改版必须开源，且禁止捆绑恶意软件。",
  "about.dmca": "查看 DMCA / 恶意捆绑声明",
  "about.thanks": "特别感谢",
  "about.thanks-desc": "本站界面使用 WinUIonWeb 的 Web 版 WinUI 控件构建",
  "about.winui-on-web": "WinUIonWeb — 在网页上还原 WinUI 的项目",
  "about.open-repo": "打开代码仓库",

  "search.placeholder": "搜索文档和全站内容…",
  "search.title": "搜索",
  "search.results-for": "搜索",
  "search.results-count": "条结果",
  "search.empty-query": "输入关键词搜索文档、教程和全站内容",
  "search.no-results": "没有找到相关结果",
  "search.no-results-desc": "换个关键词试试，例如：CPU-Z、磁盘、蓝屏、硬件信息",

  "why.title": "为什么选择图吧工具箱CE？",
  "why.subtitle": "全面对比原版图吧工具箱，图吧工具箱CE在下载体验、界面设计、兼容性、功能丰富度和智能化方面全面领先",
  "why.winner": "更优",
  "why.legacy": "原版",

  "why.dl.title": "下载方式",
  "why.dl.subtitle": "多渠道高速下载 vs 仅官网单一入口",
  "why.dl.winItems": "支持 Winget 一键命令行安装|支持微软应用商店 (Microsoft Store) 安装与自动更新|支持 GitCode 国内高速下载|支持 GitHub Releases 下载|支持夸克/百度网盘下载",
  "why.dl.legacyItems": "仅支持官网下载，国内访问速度慢|无包管理器支持，无法自动更新|下载渠道单一，容易因服务器负载导致失败",

  "why.ui.title": "软件界面",
  "why.ui.subtitle": "WinUI 3 原生 Fluent Design vs 传统易语言界面",
  "why.ui.winItems": "采用 WinUI 3 框架，原生 Windows 11 设计语言|Mica / Acrylic 毛玻璃材质背景|流畅的页面切换动画与控件过渡效果|支持亮色 / 暗色 / 跟随系统主题|自定义窗口背景图片|现代化响应式布局",
  "why.ui.legacyItems": "基于易语言的传统界面，视觉效果过时|无毛玻璃材质，无动画过渡|仅支持基础暗色模式切换|界面控件样式单一",

  "why.utf8.title": "UTF-8 兼容性",
  "why.utf8.subtitle": "完美 Unicode 支持 vs 开启 UTF-8 后运行异常",
  "why.utf8.winItems": "原生支持 UTF-8 编码，路径和文件名无乱码|中文目录名（处理器工具、显卡工具等）完美显示|.NET 10 运行时原生 Unicode 处理",
  "why.utf8.legacyItems": "开启 Windows UTF-8 全局支持后运行异常|易语言默认使用 ANSI 编码，对 UTF-8 兼容性差|中文路径可能显示乱码或无法正确解析",

  "why.tools.title": "FluentUI 内置工具",
  "why.tools.subtitle": "47 款内置工具 vs 少量基础内置功能",
  "why.tools.winItems": "垃圾清理 — Winapp2 规则库驱动的深度清理|流氓软件的克星 — 右键菜单 / 自启动 / 计划任务|游戏联机助手 — 不用公网 IP 也能和朋友联机|格式转换 — 图片 / 音视频 / 文档 / 打包 ZIP|一键三烤 — CPU / GPU / 网卡压力测试，可导出报告|端口查看、启动项管理、时间同步、Windows 镜像下载|AI 助手、CPU / GPU 天梯图、云端跑分排行",
  "why.tools.legacyItems": "内置工具数量有限|工具界面风格不统一|部分工具功能较为基础",

  "why.ai.title": "AI 智能体驱动",
  "why.ai.subtitle": "内置 AI 助手帮你解决电脑问题",
  "why.ai.winItems": "内置 AI 智能体，可回答电脑硬件和系统问题|支持多种 AI 模型接入|自然语言交互，降低使用门槛|持续迭代更新 AI 能力",
  "why.ai.legacyItems": "无 AI 功能|遇到问题需自行搜索排查",

  "why.summary.title": "图吧工具箱CE — 下一代电脑硬件检测利器",
  "why.summary.text": "从下载体验到日常使用，图吧工具箱CE在每一个维度都带来了质的飞跃。如果你还在使用原版工具箱，是时候升级了。",
  "why.summary.download": "立即下载图吧工具箱CE",

  "rank.title": "跑分排行",
  "rank.subtitle": "查看社区用户上传的性能跑分，与全球用户对比电脑性能（数据来自图吧工具箱CE社区）",
  "rank.info-title": "如何上传你的跑分？",
  "rank.info-message": "下载并安装图吧工具箱CE，运行内置的「性能测试」跑完全部项目后，点击「上传排行」即可将你的数据提交到社区排行榜。",
  "rank.sort.gaming": "游戏性能",
  "rank.sort.office": "办公性能",
  "rank.sort.cpu": "CPU 多核",
  "rank.sort.gpu": "GPU 渲染",
  "rank.sort.disk": "硬盘读取",
  "rank.sort.browser": "浏览器",
  "rank.search-placeholder": "搜索 CPU / GPU / 用户名…",
  "rank.refresh": "刷新",
  "rank.retry": "重试",
  "rank.loading": "正在加载排行榜…",
  "rank.empty": "没有符合条件的跑分记录，换个关键词试试",
  "rank.game": "游戏",
  "rank.office": "办公",
  "rank.entries": "条记录",
  "rank.page": "第",
  "rank.prev": "上一页",
  "rank.next": "下一页",
  "rank.close": "关闭",
  "rank.report-title": "的测试报告",
  "rank.detail.cpu": "CPU",
  "rank.detail.gpu": "GPU",
  "rank.detail.motherboard": "主板",
  "rank.detail.memory": "内存",
  "rank.detail.disk": "硬盘",
  "rank.detail.os": "系统",
  "rank.detail.cpu-single": "CPU 单核",
  "rank.detail.cpu-multi": "CPU 多核",
  "rank.detail.gpu-render": "GPU 渲染",
  "rank.detail.memory-cap": "内存容量",
  "rank.detail.disk-read": "硬盘顺序读",
  "rank.detail.disk-write": "硬盘顺序写",
  "rank.detail.disk-4k-read": "硬盘 4K 读",
  "rank.detail.disk-4k-write": "硬盘 4K 写",
  "rank.detail.browser": "浏览器",
  "rank.detail.submitted": "提交时间",
  "rank.detail-loading": "正在加载硬件详情…",
  "rank.detail-load-failed": "硬件详情加载失败，可稍后重试",

  "latency.title": "核间延迟查询",
  "latency.subtitle": "查看社区上传的 CPU 核间延迟热力图，对比不同处理器型号的核心间通信延迟",
  "latency.search-placeholder": "搜索 CPU / 用户名…",
  "latency.refresh": "刷新",
  "latency.retry": "重试",
  "latency.loading": "正在加载热力图列表…",
  "latency.empty": "暂无核间延迟热力图数据",
  "latency.view": "点击查看热力图",
  "latency.total": "张热力图",
  "latency.close": "关闭",
  "latency.dialog-title": "核间延迟热力图",

  "mushroom.title": "毒蘑菇测试",
  "mushroom.start": "点击开始测试"
}
